import type { InputMarketParams } from '@morpho-org/blue-sdk'
import type { Address, Client, Hex, Transport } from 'viem'

import { type BatchLensTransportType, readDeploylessBatchLens } from '@repo/utils'
import { sol, solFile } from 'soltag'

// Single-file soltag lens: reads everything a reallocation pass needs for a batch of vaults inside
// ONE eth_call against one pinned block — the vault's roles, its withdraw queue, and per market the
// params, projected Blue state, the vault's position, its cap, and the IRM's stored rateAtTarget.
//
// Accrual is projected READ-ONLY, replicating `MorphoBalancesLib.expectedMarketBalances` against the
// vendored upstream math below, rather than calling the state-changing `Morpho.accrueInterest`. The
// deployless envelope dispatches each element with STATICCALL, so a state-changing lens would revert
// every element. `borrowRateView` keeps the projection correct for any IRM, which matters because
// `equalize-utilizations` deliberately includes markets on foreign IRMs.
//
// The IRM's `rateAtTarget` cannot be advanced read-only — only Blue calling `borrowRate` moves it —
// so this returns the STORED value plus the inputs its advance needs, and the fetcher finishes the
// job with `AdaptiveCurveIrmLib`. That is sound only because the field is meaningful for the
// canonical AdaptiveCurveIRM alone, which the fetcher already gates on.
//
// The soltag type codegen (`.soltag/types.d.ts`, regenerated by the `soltag` CLI before typecheck)
// narrows the compiled `.abi`, so viem encodes the inputs and decodes the structs natively; no
// hand-written ABI fragment and no manual abi.encode/decode. Compiled to a deployless factory by
// soltag's Vitest/esbuild integrations; `sol``` throws if the transform is not active.
export const VaultV1ReallocationLens = sol('VaultV1ReallocationLens')`
// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity ^0.8.19;

${solFile('@repo/contracts/solidity/morpho/BalancesMath.sol')}

struct MarketParams { address loanToken; address collateralToken; address oracle; address irm; uint256 lltv; }
struct Market {
  uint128 totalSupplyAssets;
  uint128 totalSupplyShares;
  uint128 totalBorrowAssets;
  uint128 totalBorrowShares;
  uint128 lastUpdate;
  uint128 fee;
}
struct Position { uint256 supplyShares; uint128 borrowShares; uint128 collateral; }

interface IMorpho {
  function market(bytes32 id) external view returns (Market memory);
  function position(bytes32 id, address user) external view returns (Position memory);
  function idToMarketParams(bytes32 id) external view returns (MarketParams memory);
  function feeRecipient() external view returns (address);
}

interface IIrm {
  function borrowRateView(MarketParams memory marketParams, Market memory market) external view returns (uint256);
}

interface IMetaMorpho {
  function owner() external view returns (address);
  function curator() external view returns (address);
  function isAllocator(address target) external view returns (bool);
  function withdrawQueueLength() external view returns (uint256);
  function withdrawQueue(uint256 index) external view returns (bytes32);
  function config(bytes32 id) external view returns (uint184 cap, bool enabled, uint64 removableAt);
}

interface IAdaptiveCurveIrm { function rateAtTarget(bytes32 id) external view returns (int256); }

contract VaultV1ReallocationLens {
  uint256 internal constant VIRTUAL_SHARES = 1e6;
  uint256 internal constant VIRTUAL_ASSETS = 1;

  IMorpho public immutable MORPHO;
  address public immutable ADAPTIVE_CURVE_IRM;

  // One vault, plus the EOA whose allocator role is being probed. Role data rides the same call as
  // the market snapshot, so the tick needs no separate isAllocator read.
  struct Input { address vault; address eoa; }

  struct MarketOut {
    bytes32 id;
    MarketParams params;
    uint256 totalSupplyAssets;   // projected
    uint256 totalSupplyShares;   // projected, fee-diluted
    uint256 totalBorrowAssets;   // projected
    uint256 cap;                 // the vault's config(id).cap
    uint256 vaultAssets;         // the vault's supplyShares converted down, projected
    uint256 rateAtTargetStored;  // PRE-projection; 0 unless irm is the canonical AdaptiveCurveIRM
    uint256 utilizationBefore;   // pre-projection utilization (WAD), input to the rateAtTarget advance
    uint256 elapsed;             // block.timestamp - market.lastUpdate, the advance's other input
  }

  struct VaultOut {
    address owner;
    address curator;
    bool isAllocator;
    MarketOut[] markets;         // withdraw-queue order
  }

  constructor(IMorpho morpho, address adaptiveCurveIrm) {
    MORPHO = morpho;
    ADAPTIVE_CURVE_IRM = adaptiveCurveIrm;
  }

  // SharesMathLib.toAssetsDown: the vault's own position, rounded against the vault.
  function _toAssetsDown(uint256 shares, uint256 totalAssets, uint256 totalShares) internal pure returns (uint256) {
    return SharesMathLib.toAssetsDown(shares, totalAssets, totalShares);
  }

  // MorphoBalancesLib.expectedMarketBalances, applied in place. Mirrors upstream's guards exactly:
  // no interest when no time passed, nothing borrowed, or no IRM. Note this leaves lastUpdate
  // alone — nothing downstream reads it post-projection, and moving it would misreport elapsed.
  function _project(Market memory m, MarketParams memory params, uint256 elapsed) internal view {
    if (elapsed == 0 || m.totalBorrowAssets == 0 || params.irm == address(0)) return;

    uint256 borrowRate = IIrm(params.irm).borrowRateView(params, m);
    uint256 interest = MathLib.wMulDown(m.totalBorrowAssets, MathLib.wTaylorCompounded(borrowRate, elapsed));
    m.totalBorrowAssets += SafeCastLib.toUint128(interest);
    m.totalSupplyAssets += SafeCastLib.toUint128(interest);

    if (m.fee != 0) {
      uint256 feeAmount = MathLib.wMulDown(interest, m.fee);
      // feeAmount is subtracted from total supply here to compensate for it already being added.
      uint256 feeShares = SharesMathLib.toSharesDown(feeAmount, m.totalSupplyAssets - feeAmount, m.totalSupplyShares);
      m.totalSupplyShares += SafeCastLib.toUint128(feeShares);
    }
  }

  // The per-item entrypoint viem-dlc's envelope calls once per element. No inner try/catch, unlike
  // the liquidation lenses: no whitelisted vault is expected to be unreadable, so a revert IS that
  // vault's failure and the reader's declined:'throw' default surfaces it rather than dropping a row.
  function lens(Input calldata e) external view returns (VaultOut memory o) {
    // Fail closed: Blue credits the fee recipient's own position with the fee shares this projection
    // only mints into the total, so vaultAssets would read high for exactly that vault. No live
    // vault is the fee recipient; if one ever is, that is a deliberate change, not a silent misread.
    require(e.vault != MORPHO.feeRecipient(), "vault is fee recipient");

    IMetaMorpho vault = IMetaMorpho(e.vault);
    o.owner = vault.owner();
    o.curator = vault.curator();
    o.isAllocator = vault.isAllocator(e.eoa);

    uint256 length = vault.withdrawQueueLength();
    o.markets = new MarketOut[](length);
    for (uint256 i = 0; i < length; i++) {
      bytes32 id = vault.withdrawQueue(i);
      MarketParams memory params = MORPHO.idToMarketParams(id);
      Market memory m = MORPHO.market(id);
      Position memory p = MORPHO.position(id, e.vault);
      (uint184 cap,,) = vault.config(id);

      uint256 elapsed = block.timestamp - m.lastUpdate;
      uint256 utilizationBefore =
        m.totalSupplyAssets == 0 ? 0 : MathLib.wDivDown(m.totalBorrowAssets, m.totalSupplyAssets);

      uint256 rateAtTargetStored = 0;
      if (params.irm == ADAPTIVE_CURVE_IRM) {
        int256 signedRate = IAdaptiveCurveIrm(params.irm).rateAtTarget(id);
        if (signedRate > 0) rateAtTargetStored = uint256(signedRate);
      }

      _project(m, params, elapsed);

      o.markets[i] = MarketOut({
        id: id,
        params: params,
        totalSupplyAssets: m.totalSupplyAssets,
        totalSupplyShares: m.totalSupplyShares,
        totalBorrowAssets: m.totalBorrowAssets,
        cap: cap,
        vaultAssets: _toAssetsDown(p.supplyShares, m.totalSupplyAssets, m.totalSupplyShares),
        rateAtTargetStored: rateAtTargetStored,
        utilizationBefore: utilizationBefore,
        elapsed: elapsed
      });
    }
  }
}
`

/** One vault to read, plus the EOA whose `isAllocator` bit is wanted alongside its snapshot. */
type LensInput = { vault: Address; eoa: Address }

/** The decoded Solidity `MarketOut` struct (uint* → bigint per viem). */
type LensMarketOut = {
  id: Hex
  params: InputMarketParams
  totalSupplyAssets: bigint
  totalSupplyShares: bigint
  totalBorrowAssets: bigint
  cap: bigint
  vaultAssets: bigint
  /**
   * The IRM's **stored** rate at target, before accrual — only Blue calling `borrowRate` advances
   * it, which a read-only lens cannot do. `fetchVaultData` finishes the advance with
   * `AdaptiveCurveIrmLib`; nothing else should read this field raw.
   */
  rateAtTargetStored: bigint
  utilizationBefore: bigint
  elapsed: bigint
}

/** The decoded Solidity `VaultOut` struct. */
type LensVaultOut = {
  owner: Address
  curator: Address
  isAllocator: boolean
  markets: readonly LensMarketOut[]
}

/**
 * Reads the reallocation lens for every vault in one deployless `eth_call`, pinned to `blockNumber`
 * so the whole snapshot is coherent across markets and reproducible. Returns a map keyed by the
 * lower-cased vault address.
 *
 * Throws whatever the lens reverted with — the caller (one vault per call, see `fetchVaultData`)
 * treats that as that vault's failure. The `client` must use viem-dlc's deployless transport (built
 * by bot-kit's `createDeploylessClient`).
 */
export const readVaultV1Lens = async (
  client: Client<Transport<BatchLensTransportType>>,
  addresses: { morpho: Address; adaptiveCurveIrm: Address },
  vaults: readonly LensInput[],
  blockNumber: bigint
): Promise<Map<string, LensVaultOut>> => {
  const compiled = VaultV1ReallocationLens.with(addresses.morpho, addresses.adaptiveCurveIrm)
  // No `batch.gas`: the old polynomial fit does not carry over (the new model's `fixed` excludes the
  // copy of the chunk's own bytes, where `constant` folded in CREATE overhead), and a model viem-dlc
  // rejects as malformed is ignored silently in favour of packing by bytes. A chunk resizes from what
  // its own pages report, so stating nothing costs continuation round trips and never a result.
  // Populate from the wide event's `fixed_gas` / `item_gas_avg` / `item_gas_stddev` once observed.
  return readDeploylessBatchLens({
    client,
    parameters: {
      ...compiled,
      functionName: 'lens',
      args: vaults,
      blockNumber
    },
    key: ({ vault }) => vault.toLowerCase(),
    value: (_input, out): LensVaultOut => out
  })
}
