import type { InputMarketParams } from '@morpho-org/blue-sdk'
import type { Address, Client, Hex, Transport } from 'viem'

import { type BatchLensTransportType, readDeploylessBatchLens } from '@repo/utils'
import { sol, solFile } from 'soltag'

// Single-file soltag lens: reads everything a reallocation pass needs for a batch of vaults inside
// ONE eth_call against one pinned block — the VaultV2 factory identity, the EOA's allocator bit,
// the idle balance, every configured adapter (factory-classified by generation), and per market the
// params, accrued Blue state, the adapter's position, the IRM's rateAtTarget, and the market- and
// collateral-level cap state; the adapter-level ("this") cap state rides the same row. It replaces
// `fetchAccrualVaultV2`'s per-market fan-out plus the separate cap multicall and `isAllocator` read
// with a single billed call, and it removes the client-side accrual entirely: `Morpho.accrueInterest`
// runs inside the simulation, so every read below is exactly what the market holds at that block.
//
// `vault.totalAssets()` is read LAST: VaultV2's `accrueInterestView` sums each adapter's
// `realAssets()` — which reads the Blue positions this lens just accrued — so reading it after the
// per-market accruals yields the same value the reallocation tx's own first accrual will lock in as
// `firstTotalAssets` (the basis the contract checks relative caps against).
//
// The `lens` entrypoint is state-changing (`accrueInterest` is `nonpayable`); nothing escapes the
// `eth_call` — the simulation's writes are discarded — and `readDeploylessBatchLens` accepts
// nonpayable lens entrypoints for exactly this pattern.
//
// The soltag type codegen (`.soltag/types.d.ts`, regenerated by the `soltag` CLI before typecheck)
// narrows the compiled `.abi`, so viem encodes the inputs and decodes the structs natively; no
// hand-written ABI fragment and no manual abi.encode/decode. Compiled to a deployless factory by
// soltag's Vitest/esbuild integrations; `sol``` throws if the transform is not active.
export const VaultV2ReallocationLens = sol('VaultV2ReallocationLens')`
// SPDX-License-Identifier: GPL-2.0-or-later
pragma solidity ^0.8.19;

${solFile('@repo/contracts/solidity/morpho/BalancesMath.sol')}

struct MarketParams { address loanToken; address collateralToken; address oracle; address irm; uint256 lltv; }
struct Market {
  uint128 totalSupplyAssets;
  uint128 totalSupplyShares;
  uint128 totalBorrowAssets;
  uint128 totalBorrowShares;
  uint128 lastUpdate;
  uint128 fee;
}
struct Position { uint256 supplyShares; uint128 borrowShares; uint128 collateral; }

interface IMorpho {
  function market(bytes32 id) external view returns (Market memory);
  function position(bytes32 id, address user) external view returns (Position memory);
  function idToMarketParams(bytes32 id) external view returns (MarketParams memory);
  function feeRecipient() external view returns (address);
}

interface IIrm {
  function borrowRateView(MarketParams memory marketParams, Market memory market) external view returns (uint256);
}

interface IVaultV2 {
  function asset() external view returns (address);
  function totalAssets() external view returns (uint256);
  function isAllocator(address account) external view returns (bool);
  function adaptersLength() external view returns (uint256);
  function adapters(uint256 index) external view returns (address);
  function absoluteCap(bytes32 id) external view returns (uint256);
  function relativeCap(bytes32 id) external view returns (uint256);
  function allocation(bytes32 id) external view returns (uint256);
}

interface IVaultV2Factory { function isVaultV2(address account) external view returns (bool); }
interface IMarketV1AdapterFactory { function isMorphoMarketV1Adapter(address account) external view returns (bool); }
interface IMarketV1AdapterV2Factory { function isMorphoMarketV1AdapterV2(address account) external view returns (bool); }

// The two Morpho Blue market adapter generations enumerate their markets differently (a params list
// vs an id list) but take identical (de)allocate calldata and derive identical cap ids.
interface IMarketV1Adapter {
  function marketParamsListLength() external view returns (uint256);
  function marketParamsList(uint256 index) external view returns (MarketParams memory);
}

interface IMarketV1AdapterV2 {
  function marketIdsLength() external view returns (uint256);
  function marketIds(uint256 index) external view returns (bytes32);
  function supplyShares(bytes32 id) external view returns (uint256);
}

interface IERC20 { function balanceOf(address account) external view returns (uint256); }
interface IAdaptiveCurveIrm { function rateAtTarget(bytes32 id) external view returns (int256); }

contract VaultV2ReallocationLens {
  uint256 internal constant VIRTUAL_SHARES = 1e6;
  uint256 internal constant VIRTUAL_ASSETS = 1;

  // Factory-verified adapter generations; anything else (e.g. a MorphoVaultV1Adapter) stays 0 and
  // the fetcher fails the vault loud.
  uint8 internal constant KIND_UNKNOWN = 0;
  uint8 internal constant KIND_MARKET_V1 = 1;
  uint8 internal constant KIND_MARKET_V1_V2 = 2;

  IMorpho public immutable MORPHO;
  address public immutable ADAPTIVE_CURVE_IRM;
  IVaultV2Factory public immutable VAULT_V2_FACTORY;
  address public immutable MARKET_V1_ADAPTER_FACTORY;
  address public immutable MARKET_V1_ADAPTER_V2_FACTORY;

  // One vault, plus the EOA whose allocator bit is being probed. Role data rides the same call as
  // the market snapshot, so the tick needs no separate isAllocator read.
  struct Input { address vault; address eoa; }

  // One cap id's state, exactly the triple the vault enforces (de)allocations against.
  struct CapsOut { uint256 absoluteCap; uint256 relativeCap; uint256 allocation; }

  struct AdapterOut { address adapter; uint8 kind; }

  struct MarketOut {
    bytes32 id;
    bytes32 capId;               // keccak256(abi.encode("this/marketParams", adapter, params))
    MarketParams params;
    uint256 totalSupplyAssets;   // projected
    uint256 totalSupplyShares;   // projected, fee-diluted
    uint256 totalBorrowAssets;   // projected
    CapsOut cap;                 // the market's own cap id
    CapsOut collateralCap;       // keccak256(abi.encode("collateralToken", collateral)); deduped client-side
    uint256 vaultAssets;         // the adapter's supply shares converted down, projected
    uint256 rateAtTargetStored;  // PRE-projection; 0 unless irm is the canonical AdaptiveCurveIRM
    uint256 utilizationBefore;   // pre-projection utilization (WAD), input to the rateAtTarget advance
    uint256 elapsed;             // block.timestamp - market.lastUpdate, the advance's other input
  }

  struct VaultOut {
    bool isVaultV2;              // factory identity; when false every other field is left zeroed
    bool isAllocator;
    uint256 totalAssets;         // post-accrual (see the module comment on read ordering)
    uint256 idleAssets;          // asset.balanceOf(vault)
    AdapterOut[] adapters;
    CapsOut adapterCap;          // keccak256(abi.encode("this", adapter)); zeroed unless one market adapter qualifies
    MarketOut[] markets;         // enumeration order of the single qualifying adapter
  }

  constructor(
    IMorpho morpho,
    address adaptiveCurveIrm,
    IVaultV2Factory vaultV2Factory,
    address marketV1AdapterFactory,
    address marketV1AdapterV2Factory
  ) {
    MORPHO = morpho;
    ADAPTIVE_CURVE_IRM = adaptiveCurveIrm;
    VAULT_V2_FACTORY = vaultV2Factory;
    MARKET_V1_ADAPTER_FACTORY = marketV1AdapterFactory;
    MARKET_V1_ADAPTER_V2_FACTORY = marketV1AdapterV2Factory;
  }

  // SharesMathLib.toAssetsDown: the adapter's own position, rounded against the vault.
  function _toAssetsDown(uint256 shares, uint256 totalAssets, uint256 totalShares) internal pure returns (uint256) {
    return SharesMathLib.toAssetsDown(shares, totalAssets, totalShares);
  }

  // MorphoBalancesLib.expectedMarketBalances, applied in place. Mirrors upstream's guards exactly:
  // no interest when no time passed, nothing borrowed, or no IRM.
  function _project(Market memory m, MarketParams memory params, uint256 elapsed) internal view {
    if (elapsed == 0 || m.totalBorrowAssets == 0 || params.irm == address(0)) return;

    uint256 borrowRate = IIrm(params.irm).borrowRateView(params, m);
    uint256 interest = MathLib.wMulDown(m.totalBorrowAssets, MathLib.wTaylorCompounded(borrowRate, elapsed));
    m.totalBorrowAssets += SafeCastLib.toUint128(interest);
    m.totalSupplyAssets += SafeCastLib.toUint128(interest);

    if (m.fee != 0) {
      uint256 feeAmount = MathLib.wMulDown(interest, m.fee);
      // feeAmount is subtracted from total supply here to compensate for it already being added.
      uint256 feeShares = SharesMathLib.toSharesDown(feeAmount, m.totalSupplyAssets - feeAmount, m.totalSupplyShares);
      m.totalSupplyShares += SafeCastLib.toUint128(feeShares);
    }
  }

  // The per-item entrypoint viem-dlc's envelope calls once per element. No inner try/catch, unlike
  // the liquidation lenses: no whitelisted vault is expected to be unreadable, so a revert IS that
  // vault's failure and the reader's declined:'throw' default surfaces it rather than dropping a row.
  // A non-VaultV2 address is data, not a failure — it comes back as isVaultV2=false.

  function _adapterKind(address adapter) internal view returns (uint8) {
    if (
      MARKET_V1_ADAPTER_FACTORY != address(0) &&
      IMarketV1AdapterFactory(MARKET_V1_ADAPTER_FACTORY).isMorphoMarketV1Adapter(adapter)
    ) return KIND_MARKET_V1;
    if (
      MARKET_V1_ADAPTER_V2_FACTORY != address(0) &&
      IMarketV1AdapterV2Factory(MARKET_V1_ADAPTER_V2_FACTORY).isMorphoMarketV1AdapterV2(adapter)
    ) return KIND_MARKET_V1_V2;
    return KIND_UNKNOWN;
  }

  function _caps(IVaultV2 vault, bytes32 id) internal view returns (CapsOut memory) {
    return CapsOut({
      absoluteCap: vault.absoluteCap(id),
      relativeCap: vault.relativeCap(id),
      allocation: vault.allocation(id)
    });
  }

  function lens(Input calldata e) external view returns (VaultOut memory o) {
    o.isVaultV2 = VAULT_V2_FACTORY.isVaultV2(e.vault);
    // Nothing else about a non-factory address is safe to call; the fetcher rejects on this bit.
    if (!o.isVaultV2) return o;

    IVaultV2 vault = IVaultV2(e.vault);
    o.isAllocator = vault.isAllocator(e.eoa);
    o.idleAssets = IERC20(vault.asset()).balanceOf(e.vault);

    uint256 count = vault.adaptersLength();
    o.adapters = new AdapterOut[](count);
    uint256 qualifying = 0;
    uint256 marketAdapterIndex = 0;
    for (uint256 i = 0; i < count; i++) {
      address adapter = vault.adapters(i);
      uint8 kind = _adapterKind(adapter);
      o.adapters[i] = AdapterOut({ adapter: adapter, kind: kind });
      if (kind != KIND_UNKNOWN) {
        qualifying++;
        marketAdapterIndex = i;
      }
    }

    // Markets are read only for the shape the bot supports (one adapter, and it is a Morpho Blue
    // market adapter); any other shape returns bare adapter rows for the fetcher's error message.
    if (count == 1 && qualifying == 1) {
      AdapterOut memory qualified = o.adapters[marketAdapterIndex];
      o.markets = qualified.kind == KIND_MARKET_V1
        ? _readV1Markets(vault, qualified.adapter)
        : _readV2Markets(vault, qualified.adapter);
      o.adapterCap = _caps(vault, keccak256(abi.encode("this", qualified.adapter)));
    }

    // Unaffected by the switch to a read-only projection: totalAssets folds each adapter's
    // realAssets, which already projects interest itself rather than relying on a prior accrual.
    o.totalAssets = vault.totalAssets();
  }

  function _readV1Markets(IVaultV2 vault, address adapter) internal view returns (MarketOut[] memory markets) {
    // Fail closed, but only for the generation this can bite. The legacy adapter holds a Blue
    // POSITION, and Blue credits the fee recipient's position with the fee shares this projection
    // only mints into the market total — so vaultAssets would read low for exactly that adapter.
    // MorphoMarketV1AdapterV2 keeps its own supplyShares, which Blue's accrual never touches, so
    // rejecting it too would be downtime for nothing.
    require(adapter != MORPHO.feeRecipient(), "adapter is fee recipient");

    uint256 length = IMarketV1Adapter(adapter).marketParamsListLength();
    markets = new MarketOut[](length);
    for (uint256 i = 0; i < length; i++) {
      MarketParams memory params = IMarketV1Adapter(adapter).marketParamsList(i);
      // MarketParamsLib.id: the Blue market id is the hash of its params.
      bytes32 id = keccak256(abi.encode(params));
      markets[i] = _readMarket(vault, adapter, id, params, MORPHO.position(id, adapter).supplyShares);
    }
  }

  function _readV2Markets(IVaultV2 vault, address adapter) internal view returns (MarketOut[] memory markets) {
    uint256 length = IMarketV1AdapterV2(adapter).marketIdsLength();
    markets = new MarketOut[](length);
    for (uint256 i = 0; i < length; i++) {
      bytes32 id = IMarketV1AdapterV2(adapter).marketIds(i);
      markets[i] = _readMarket(
        vault,
        adapter,
        id,
        MORPHO.idToMarketParams(id),
        IMarketV1AdapterV2(adapter).supplyShares(id)
      );
    }
  }

  function _readMarket(
    IVaultV2 vault,
    address adapter,
    bytes32 id,
    MarketParams memory params,
    uint256 shares
  ) internal view returns (MarketOut memory o) {
    Market memory m = MORPHO.market(id);

    o.id = id;
    o.params = params;
    o.elapsed = block.timestamp - m.lastUpdate;
    o.utilizationBefore =
      m.totalSupplyAssets == 0 ? 0 : MathLib.wDivDown(m.totalBorrowAssets, m.totalSupplyAssets);

    // Read BEFORE projecting: this is the IRM's stored value, which only Blue calling borrowRate
    // advances. The fetcher finishes the advance with AdaptiveCurveIrmLib.
    if (params.irm == ADAPTIVE_CURVE_IRM) {
      int256 signedRate = IAdaptiveCurveIrm(params.irm).rateAtTarget(id);
      if (signedRate > 0) o.rateAtTargetStored = uint256(signedRate);
    }

    _project(m, params, o.elapsed);

    o.totalSupplyAssets = m.totalSupplyAssets;
    o.totalSupplyShares = m.totalSupplyShares;
    o.totalBorrowAssets = m.totalBorrowAssets;
    o.vaultAssets = _toAssetsDown(shares, m.totalSupplyAssets, m.totalSupplyShares);

    o.capId = keccak256(abi.encode("this/marketParams", adapter, params));
    o.cap = _caps(vault, o.capId);
    o.collateralCap = _caps(vault, keccak256(abi.encode("collateralToken", params.collateralToken)));
  }
}
`

/** One vault to read, plus the EOA whose `isAllocator` bit is wanted alongside its snapshot. */
type LensInput = { vault: Address; eoa: Address }

/** The decoded Solidity `CapsOut` struct. */
export type LensCapsOut = {
  absoluteCap: bigint
  relativeCap: bigint
  allocation: bigint
}

/** The decoded Solidity `AdapterOut` struct; `kind` follows the lens's KIND_* constants. */
export type LensAdapterOut = {
  adapter: Address
  kind: number
}

/** The decoded Solidity `MarketOut` struct (uint* → bigint per viem). */
export type LensMarketOut = {
  id: Hex
  capId: Hex
  params: InputMarketParams
  totalSupplyAssets: bigint
  totalSupplyShares: bigint
  totalBorrowAssets: bigint
  cap: LensCapsOut
  collateralCap: LensCapsOut
  vaultAssets: bigint
  /**
   * The IRM's **stored** rate at target, before accrual — only Blue calling `borrowRate` advances
   * it, which a read-only lens cannot do. `fetchVaultV2Data` finishes the advance with
   * `AdaptiveCurveIrmLib`; nothing else should read this field raw.
   */
  rateAtTargetStored: bigint
  utilizationBefore: bigint
  elapsed: bigint
}

/** The decoded Solidity `VaultOut` struct. */
export type LensVaultOut = {
  isVaultV2: boolean
  isAllocator: boolean
  totalAssets: bigint
  idleAssets: bigint
  adapters: readonly LensAdapterOut[]
  adapterCap: LensCapsOut
  markets: readonly LensMarketOut[]
}

export const KIND_UNKNOWN = 0

/**
 * Reads the reallocation lens for every vault in one deployless `eth_call`, pinned to `blockNumber`
 * so the whole snapshot is coherent across markets and reproducible. Returns a map keyed by the
 * lower-cased vault address.
 *
 * Throws whatever the lens reverted with — the caller (one vault per call, see `fetchVaultV2Data`)
 * treats that as that vault's failure. The `client` must use viem-dlc's deployless transport (built
 * by bot-kit's `createDeploylessClient`).
 */
export const readVaultV2Lens = async (
  client: Client<Transport<BatchLensTransportType>>,
  addresses: {
    morpho: Address
    adaptiveCurveIrm: Address
    vaultV2Factory: Address
    marketV1AdapterFactory: Address
    marketV1AdapterV2Factory: Address
  },
  vaults: readonly LensInput[],
  blockNumber: bigint
): Promise<Map<string, LensVaultOut>> => {
  const compiled = VaultV2ReallocationLens.with(
    addresses.morpho,
    addresses.adaptiveCurveIrm,
    addresses.vaultV2Factory,
    addresses.marketV1AdapterFactory,
    addresses.marketV1AdapterV2Factory
  )
  // No `batch.gas`: the old polynomial fit does not carry over (the new model's `fixed` excludes the
  // copy of the chunk's own bytes, where `constant` folded in CREATE overhead), and a model viem-dlc
  // rejects as malformed is ignored silently in favour of packing by bytes. A chunk resizes from what
  // its own pages report, so stating nothing costs continuation round trips and never a result.
  // Populate from the wide event's `fixed_gas` / `item_gas_avg` / `item_gas_stddev` once observed.
  return readDeploylessBatchLens({
    client,
    parameters: {
      ...compiled,
      functionName: 'lens',
      args: vaults,
      blockNumber
    },
    key: ({ vault }) => vault.toLowerCase(),
    value: (_input, out): LensVaultOut => out
  })
}
